#include <iostream>
#include <stdio.h>
#include <conio.h>
#include <vector>
#include <functional>
#include <map>
#include <utility>
#include "cursorMovement.h"
#include "screenHandle.h"
#include "optionGenerator.h"
#include "optionSelector.h"
#include "screen.h"
